-- V97__Create_Member_User_Accounts.sql
-- DEPRECATED: This migration is no longer used
-- 
-- User accounts for members are now created by:
-- 1. BulkProcessingService.createMemberLoginCredentials() during bulk member upload
-- 2. MemberService.createMemberUserAccount() during individual member onboarding
-- 3. Java-based migration V103 for migrated members (EMP019, EMP020)
--
-- The Java-based migration properly encodes the National ID using BCryptPasswordEncoder (strength 10)
-- This ensures passwords are correctly hashed and can be verified during login
-- 
-- Login credentials for members:
-- - Username: memberNumber (e.g., EMP019)
-- - Password: National ID (e.g., 11111111) - encoded with BCrypt
